spring:
  application:
    name: API-GATEWAY
    
  cloud :
    gateway:
       routes:
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
            - Path=/user/**  
         - id: HOTEL-SERVICE
           uri: lb://HOTEL-SERVICE
           predicates:
            - Path=/hotel/**,/staffs/**
         - id: RATING-SERVICE
           uri: lb://RATING-SERVICE
           predicates:
            - Path=/ratings/**
            
server :
   port: 8085
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true
  service-url :
   defaultZone: http://localhost:8761/eureka